// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package db

import (
	"context"
)

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invitation_tokens (id, email_encrypted, role, token_hash, expires_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateInviteParams struct {
	ID             string `json:"id"`
	EmailEncrypted []byte `json:"email_encrypted"`
	Role           string `json:"role"`
	TokenHash      string `json:"token_hash"`
	ExpiresAt      string `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.ExecContext(ctx, createInvite,
		arg.ID,
		arg.EmailEncrypted,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, email_encrypted, role, token_hash, expires_at, used
FROM invitation_tokens
WHERE token_hash = ?
  AND used = FALSE
  AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (InvitationToken, error) {
	row := q.db.QueryRowContext(ctx, getInviteByTokenHash, tokenHash)
	var i InvitationToken
	err := row.Scan(
		&i.ID,
		&i.EmailEncrypted,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const markInviteUsed = `-- name: MarkInviteUsed :exec
UPDATE invitation_tokens SET used = TRUE WHERE id = ?
`

func (q *Queries) MarkInviteUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markInviteUsed, id)
	return err
}
