// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invitation_tokens (id, email, role, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateInviteParams struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite,
		arg.ID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, email, role, token_hash, expires_at, used
FROM invitation_tokens
WHERE token_hash = $1
  AND used = FALSE
  AND expires_at > NOW()
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (InvitationToken, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i InvitationToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const markInviteUsed = `-- name: MarkInviteUsed :exec
UPDATE invitation_tokens SET used = TRUE WHERE id = $1
`

func (q *Queries) MarkInviteUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markInviteUsed, id)
	return err
}
