// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
)

type AdminUser struct {
	ID             string         `json:"id"`
	Username       string         `json:"username"`
	EmailHmac      string         `json:"email_hmac"`
	EmailEncrypted []byte         `json:"email_encrypted"`
	PasswordHash   string         `json:"password_hash"`
	Role           string         `json:"role"`
	Status         string         `json:"status"`
	CreatedAt      string         `json:"created_at"`
	LastLoginAt    sql.NullString `json:"last_login_at"`
}

type AuditLog struct {
	ID        int64          `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	Action    string         `json:"action"`
	Detail    sql.NullString `json:"detail"`
	CreatedAt string         `json:"created_at"`
}

type InvitationToken struct {
	ID             string `json:"id"`
	EmailEncrypted []byte `json:"email_encrypted"`
	Role           string `json:"role"`
	TokenHash      string `json:"token_hash"`
	ExpiresAt      string `json:"expires_at"`
	Used           int64  `json:"used"`
}

type PasswordResetToken struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	TokenHash string `json:"token_hash"`
	ExpiresAt string `json:"expires_at"`
	Used      int64  `json:"used"`
}

type ReportSchema struct {
	ID        int64           `json:"id"`
	Version   int64           `json:"version"`
	IsLive    int64           `json:"is_live"`
	Schema    json.RawMessage `json:"schema"`
	UpdatedAt string          `json:"updated_at"`
	UpdatedBy sql.NullString  `json:"updated_by"`
}

type Session struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type Setting struct {
	ID        int64  `json:"id"`
	Data      []byte `json:"data"`
	UpdatedAt string `json:"updated_at"`
}
