// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveSuperAdmins(ctx context.Context) (int64, error)
	CountAdminUsers(ctx context.Context) (int64, error)
	CountReportSchemas(ctx context.Context) (int64, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	DeleteAdminUser(ctx context.Context, id string) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSessionsByUserID(ctx context.Context, userID string) error
	DemoteLiveSchemas(ctx context.Context) error
	GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error)
	GetAdminUserByID(ctx context.Context, id string) (GetAdminUserByIDRow, error)
	GetAdminUserRoleByID(ctx context.Context, id string) (string, error)
	GetReportSchema(ctx context.Context, isLive bool) ([]byte, error)
	GetSessionUserID(ctx context.Context, id string) (string, error)
	GetSettings(ctx context.Context) ([]byte, error)
	InsertReportSchema(ctx context.Context, arg InsertReportSchemaParams) error
	InsertReportSchemaRow(ctx context.Context, arg InsertReportSchemaRowParams) error
	ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error)
	PromoteLatestDraft(ctx context.Context, updatedBy pgtype.Text) error
	UpdateAdminUserLastLogin(ctx context.Context, id string) error
	UpdateAdminUserPassword(ctx context.Context, arg UpdateAdminUserPasswordParams) error
	UpdateAdminUserRoleAndStatus(ctx context.Context, arg UpdateAdminUserRoleAndStatusParams) error
	UpsertSettings(ctx context.Context, data []byte) error
}

var _ Querier = (*Queries)(nil)
