// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_events.sql

package db

import (
	"context"
)

const countAllReportEvents = `-- name: CountAllReportEvents :one
SELECT COUNT(*) FROM report_events
`

func (q *Queries) CountAllReportEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllReportEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReportEventsSince = `-- name: CountReportEventsSince :one
SELECT COUNT(*) FROM report_events WHERE submitted_at >= ?
`

func (q *Queries) CountReportEventsSince(ctx context.Context, submittedAt string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReportEventsSince, submittedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertReportEvent = `-- name: InsertReportEvent :exec
INSERT INTO report_events (submitted_at, fields_filled)
VALUES (CURRENT_TIMESTAMP, ?)
`

func (q *Queries) InsertReportEvent(ctx context.Context, fieldsFilled string) error {
	_, err := q.db.ExecContext(ctx, insertReportEvent, fieldsFilled)
	return err
}

const latestReportEventTime = `-- name: LatestReportEventTime :one
SELECT submitted_at FROM report_events ORDER BY submitted_at DESC LIMIT 1
`

func (q *Queries) LatestReportEventTime(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, latestReportEventTime)
	var submitted_at string
	err := row.Scan(&submitted_at)
	return submitted_at, err
}

const reportEventsByDay = `-- name: ReportEventsByDay :many
SELECT date(submitted_at) AS day, CAST(COUNT(*) AS INTEGER) AS count
FROM report_events
WHERE submitted_at >= ?
GROUP BY date(submitted_at)
ORDER BY day ASC
`

type ReportEventsByDayRow struct {
	Day   interface{} `json:"day"`
	Count int64       `json:"count"`
}

func (q *Queries) ReportEventsByDay(ctx context.Context, submittedAt string) ([]ReportEventsByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, reportEventsByDay, submittedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportEventsByDayRow{}
	for rows.Next() {
		var i ReportEventsByDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
