// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schema.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReportSchemas = `-- name: CountReportSchemas :one
SELECT COUNT(*) FROM report_schema
`

func (q *Queries) CountReportSchemas(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countReportSchemas)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const demoteLiveSchemas = `-- name: DemoteLiveSchemas :exec
UPDATE report_schema SET is_live = FALSE WHERE is_live = TRUE
`

func (q *Queries) DemoteLiveSchemas(ctx context.Context) error {
	_, err := q.db.Exec(ctx, demoteLiveSchemas)
	return err
}

const getReportSchema = `-- name: GetReportSchema :one
SELECT schema FROM report_schema
WHERE is_live = $1
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetReportSchema(ctx context.Context, isLive bool) ([]byte, error) {
	row := q.db.QueryRow(ctx, getReportSchema, isLive)
	var schema []byte
	err := row.Scan(&schema)
	return schema, err
}

const insertReportSchema = `-- name: InsertReportSchema :exec
INSERT INTO report_schema (version, is_live, schema, updated_at, updated_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertReportSchemaParams struct {
	Version   int32              `json:"version"`
	IsLive    bool               `json:"is_live"`
	Schema    []byte             `json:"schema"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.Text        `json:"updated_by"`
}

func (q *Queries) InsertReportSchema(ctx context.Context, arg InsertReportSchemaParams) error {
	_, err := q.db.Exec(ctx, insertReportSchema,
		arg.Version,
		arg.IsLive,
		arg.Schema,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}

const insertReportSchemaRow = `-- name: InsertReportSchemaRow :exec
INSERT INTO report_schema (version, is_live, schema, updated_at)
VALUES ($1, $2, $3, NOW())
`

type InsertReportSchemaRowParams struct {
	Version int32  `json:"version"`
	IsLive  bool   `json:"is_live"`
	Schema  []byte `json:"schema"`
}

func (q *Queries) InsertReportSchemaRow(ctx context.Context, arg InsertReportSchemaRowParams) error {
	_, err := q.db.Exec(ctx, insertReportSchemaRow, arg.Version, arg.IsLive, arg.Schema)
	return err
}

const promoteLatestDraft = `-- name: PromoteLatestDraft :exec
UPDATE report_schema
SET is_live = TRUE, updated_by = $1, updated_at = NOW()
WHERE id = (
    SELECT id FROM report_schema
    WHERE is_live = FALSE
    ORDER BY id DESC
    LIMIT 1
)
`

func (q *Queries) PromoteLatestDraft(ctx context.Context, updatedBy pgtype.Text) error {
	_, err := q.db.Exec(ctx, promoteLatestDraft, updatedBy)
	return err
}
