// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schema.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countReportSchemas = `-- name: CountReportSchemas :one
SELECT COUNT(*) FROM report_schema
`

func (q *Queries) CountReportSchemas(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReportSchemas)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDraftSchemas = `-- name: DeleteDraftSchemas :exec
DELETE FROM report_schema WHERE is_live = 0
`

func (q *Queries) DeleteDraftSchemas(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteDraftSchemas)
	return err
}

const demoteLiveSchemas = `-- name: DemoteLiveSchemas :exec
UPDATE report_schema SET is_live = 0 WHERE is_live = 1
`

func (q *Queries) DemoteLiveSchemas(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, demoteLiveSchemas)
	return err
}

const getReportSchema = `-- name: GetReportSchema :one

SELECT schema FROM report_schema
WHERE is_live = ?
ORDER BY id DESC
LIMIT 1
`

// -- name: GetReportSchema :one
// SELECT schema FROM report_schema
// WHERE is_live = ?
// ORDER BY id DESC
// LIMIT 1;
//
// -- name: CountReportSchemas :one
// SELECT COUNT(*) FROM report_schema;
//
//	-- name: DeleteDraftSchemas :exec
//	DELETE FROM report_schema WHERE is_live = 0;
//
//	-- name: InsertDraftSchema :exec
//	INSERT INTO report_schema (version, is_live, schema, updated_at, updated_by)
//	VALUES (?, 0, ?, CURRENT_TIMESTAMP, ?);
//
// -- name: DemoteLiveSchemas :exec
// UPDATE report_schema SET is_live = FALSE WHERE is_live = TRUE;
//
// -- name: PromoteLatestDraft :exec
// UPDATE report_schema
// SET is_live = TRUE, updated_by = ?, updated_at = CURRENT_TIMESTAMP
// WHERE id = (
//
//	SELECT id FROM report_schema
//	WHERE is_live = FALSE
//	ORDER BY id DESC
//	LIMIT 1
//
// );
func (q *Queries) GetReportSchema(ctx context.Context, isLive int64) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getReportSchema, isLive)
	var schema json.RawMessage
	err := row.Scan(&schema)
	return schema, err
}

const insertDraftSchema = `-- name: InsertDraftSchema :exec
INSERT INTO report_schema (version, is_live, schema, updated_at, updated_by)
VALUES (?1, 0, ?2, CURRENT_TIMESTAMP, ?3)
`

type InsertDraftSchemaParams struct {
	Version    int64           `json:"version"`
	SchemaData json.RawMessage `json:"schema_data"`
	UpdatedBy  sql.NullString  `json:"updated_by"`
}

func (q *Queries) InsertDraftSchema(ctx context.Context, arg InsertDraftSchemaParams) error {
	_, err := q.db.ExecContext(ctx, insertDraftSchema, arg.Version, arg.SchemaData, arg.UpdatedBy)
	return err
}

const promoteLatestDraft = `-- name: PromoteLatestDraft :exec
UPDATE report_schema
SET is_live = 1, updated_by = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = (
    SELECT id FROM report_schema
    WHERE is_live = 0
    ORDER BY id DESC
    LIMIT 1
)
`

func (q *Queries) PromoteLatestDraft(ctx context.Context, updatedBy sql.NullString) error {
	_, err := q.db.ExecContext(ctx, promoteLatestDraft, updatedBy)
	return err
}
