// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSuperAdmins = `-- name: CountActiveSuperAdmins :one
SELECT COUNT(*) FROM admin_users
WHERE role = 'super_admin' AND status = 'active'
`

func (q *Queries) CountActiveSuperAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSuperAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*) FROM admin_users
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :exec
INSERT INTO admin_users (id, username, email_hmac, email_encrypted, password_hash, role)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAdminUserParams struct {
	ID             string `json:"id"`
	Username       string `json:"username"`
	EmailHmac      string `json:"email_hmac"`
	EmailEncrypted []byte `json:"email_encrypted"`
	PasswordHash   string `json:"password_hash"`
	Role           string `json:"role"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error {
	_, err := q.db.Exec(ctx, createAdminUser,
		arg.ID,
		arg.Username,
		arg.EmailHmac,
		arg.EmailEncrypted,
		arg.PasswordHash,
		arg.Role,
	)
	return err
}

const deleteAdminUser = `-- name: DeleteAdminUser :exec
DELETE FROM admin_users WHERE id = $1
`

func (q *Queries) DeleteAdminUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAdminUser, id)
	return err
}

const getAdminUserByEmailHMAC = `-- name: GetAdminUserByEmailHMAC :one
SELECT id, username, email_encrypted, email_hmac, password_hash, role, status, created_at, last_login_at
FROM admin_users
WHERE email_hmac = $1
`

type GetAdminUserByEmailHMACRow struct {
	ID             string             `json:"id"`
	Username       string             `json:"username"`
	EmailEncrypted []byte             `json:"email_encrypted"`
	EmailHmac      string             `json:"email_hmac"`
	PasswordHash   string             `json:"password_hash"`
	Role           string             `json:"role"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) GetAdminUserByEmailHMAC(ctx context.Context, emailHmac string) (GetAdminUserByEmailHMACRow, error) {
	row := q.db.QueryRow(ctx, getAdminUserByEmailHMAC, emailHmac)
	var i GetAdminUserByEmailHMACRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.EmailEncrypted,
		&i.EmailHmac,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAdminUserByID = `-- name: GetAdminUserByID :one
SELECT id, username, role, status, created_at, last_login_at
FROM admin_users
WHERE id = $1
`

type GetAdminUserByIDRow struct {
	ID          string             `json:"id"`
	Username    string             `json:"username"`
	Role        string             `json:"role"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) GetAdminUserByID(ctx context.Context, id string) (GetAdminUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminUserByID, id)
	var i GetAdminUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAdminUserByUsername = `-- name: GetAdminUserByUsername :one
SELECT id, username, email_encrypted, email_hmac, password_hash, role, status, created_at, last_login_at
FROM admin_users
WHERE username = $1
`

type GetAdminUserByUsernameRow struct {
	ID             string             `json:"id"`
	Username       string             `json:"username"`
	EmailEncrypted []byte             `json:"email_encrypted"`
	EmailHmac      string             `json:"email_hmac"`
	PasswordHash   string             `json:"password_hash"`
	Role           string             `json:"role"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) GetAdminUserByUsername(ctx context.Context, username string) (GetAdminUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getAdminUserByUsername, username)
	var i GetAdminUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.EmailEncrypted,
		&i.EmailHmac,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAdminUserEmailEncryptedByID = `-- name: GetAdminUserEmailEncryptedByID :one
SELECT email_encrypted FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminUserEmailEncryptedByID(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAdminUserEmailEncryptedByID, id)
	var email_encrypted []byte
	err := row.Scan(&email_encrypted)
	return email_encrypted, err
}

const getAdminUserRoleByID = `-- name: GetAdminUserRoleByID :one
SELECT role FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminUserRoleByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getAdminUserRoleByID, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, username, role, status, created_at, last_login_at
FROM admin_users
ORDER BY created_at
`

type ListAdminUsersRow struct {
	ID          string             `json:"id"`
	Username    string             `json:"username"`
	Role        string             `json:"role"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminUserLastLogin = `-- name: UpdateAdminUserLastLogin :exec
UPDATE admin_users SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateAdminUserLastLogin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateAdminUserLastLogin, id)
	return err
}

const updateAdminUserPassword = `-- name: UpdateAdminUserPassword :exec
UPDATE admin_users SET password_hash = $1 WHERE id = $2
`

type UpdateAdminUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateAdminUserPassword(ctx context.Context, arg UpdateAdminUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateAdminUserRoleAndStatus = `-- name: UpdateAdminUserRoleAndStatus :exec
UPDATE admin_users SET role = $1, status = $2 WHERE id = $3
`

type UpdateAdminUserRoleAndStatusParams struct {
	Role   string `json:"role"`
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateAdminUserRoleAndStatus(ctx context.Context, arg UpdateAdminUserRoleAndStatusParams) error {
	_, err := q.db.Exec(ctx, updateAdminUserRoleAndStatus, arg.Role, arg.Status, arg.ID)
	return err
}
